version: "3.8"

services:
  # === MySQL Database ===
  mysql:
    image: mysql:8
    ports:
      - "3307:3306" # hostPort:containerPort
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sidangskripsi
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet

  # === Laravel Frontend ===
  frontend:
    build:
      context: ./frontend
    ports:
      - "9700:9700"
    depends_on:
      - mysql
    networks:
      - appnet

  # === CI4 Backend ===
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - appnet


  # === NGINX Reverse Proxy ===
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - appnet
    restart: always

volumes:
  mysql-data:

networks:
  appnet:
    driver: bridge
